format = """$directory$git_branch$git_status$aws$jobs$cmd_duration$line_break$character"""

add_newline = true
palette = 'gruvbox'

[directory]
style = 'bold fg:blue'
format = '[→ $path]($style)[$read_only]($read_only_style) '
truncation_length = 1
read_only = ' 󰌾'

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[$symbol  $branch(:$remote_branch)]($style)'

[git_status]
style = 'fg:yellow'
format = '( [$all_status$ahead_behind]($style))'


[aws]
symbol = ' '
style = 'fg:orange'
format = '[$symbol$profile]($style) '

[kubernetes]
disabled = true

[jobs]
symbol = ''
style = 'fg:red'
number_threshold = 1
format = '[$symbol]($style) '

[cmd_duration]
min_time = 2000
style = 'fg:gray'
format = '[$duration]($style) '

[character]
success_symbol = '[❯](fg:green)'
error_symbol = '[❯](fg:red)'

# Disable unused modules
[java]
disabled = true
[python]
disabled = true
[lua]
disabled = true
[nodejs]
disabled = true
[golang]
disabled = true
[haskell]
disabled = true
[rust]
disabled = true
[ruby]
disabled = true
[package]
disabled = true

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white = '#D8DEE9'

[palettes.onedark]
dark_blue = '#61afef'
blue = '#56b6c2'
red = '#e06c75'
green = '#98c379'
purple = '#c678dd'
cyan = '#56b6c2'
orange = '#be5046'
yellow = '#e5c07b'
gray = '#828997'
white = '#abb2bf'
black = '#2c323c'

[palettes.gruvbox]
dark_blue = '#458588'
blue = '#83a598'
teal = '#8ec07c'
red = '#fb4934'
orange = '#fe8019'
green = '#b8bb26'
yellow = '#fabd2f'
purple = '#d3869b'
gray = '#928374'
black = '#282828'
white = '#fbf1c7'

[palettes.catppuccin]
dark_blue = '#89b4fa'
blue = '#74c7ec'
teal = '#94e2d5'
red = '#f38ba8'
orange = '#fab387'
green = '#a6e3a1'
yellow = '#f9e2af'
purple = '#cba6f7'
gray = '#6c7086'
black = '#1e1e2e'
white = '#cdd6f4'
